lista: # Gerar executável com base na implementação da fila com lista encadeada.
	gcc filaComLista.c Testador.c produto.c -o Testador

vetor: # Gerar executável com base na implementação da fila com vetor.
	gcc filaComVetor.c Testador.c produto.c -o Testador

run:
	valgrind ./Testador
